### ISSUE TITLE
Differences with Retrofit?

### ISSUE THREAD

**Issue by bryant1410** [amitshekhariitbhu/AndroidNetworking#1]
Maybe you should explain what are the differences between this library and Retrofit.

**Comment by amitshekhariitbhu** [comment]
@bryant1410  Thanks for pointing out this.
I have updated the Readme.md file.
* OkHttpClient can be customized for every request easily.
* Complete analytics of any request can be obtained.
* Getting current bandwidth and connection quality can be obtained to decide logic of code.
* Executor can be passed to any request to get response in another thread.
* Single library for all type of networking.
* Prefetching of any request can be done so that it gives instant data when required from cache.
* All types of customization is possible

**Comment by bryant1410** [comment]
And do you have any performance comparison with Retrofit?

**Comment by amitshekhariitbhu** [comment]
@bryant1410  : performance is same as both uses OkHttp but Android Networking gives some extra features.

**Comment by bryant1410** [comment]
You can give a performance test to probe that. And to pretend that people use your library.

**Comment by amitshekhariitbhu** [comment]
@bryant1410  surely I will add that.

**Comment by hendrawd** [comment]
If you can create performance test comparing this library with Volley or Retrofit, it will be better i think. This library is looks promising with a lot of features in single library, but of course as a developer we need to make our application is good in performance too.

**Comment by boyfox** [comment]
+ and very easy to using and fast, very comfortable to developers. Thank you @amitshekhariitbhu for great library, need recommend this for Google, need add this library to android such as default http library. And need add some functionalities to this library such as : adding dependency executing http request and communication its, and managing response results with hierarchy. For example send request1 with request2 in parallel and if results both ok then do execute request4 otherwise call to callback. This is great functions and exists in SWIFT(for ios developers).

**Comment by amitshekhariitbhu** [comment]
@boyfox  we will the feature of merging two requests in the upcoming release.

**Comment by kunalmangela** [comment]
My Code for simple get method is not working it is give me error
url="http://dev.efurtherance.com/rcis_school_new/webservice/system/all"
param=school_code
 AndroidNetworking.get("http://dev.efurtherance.com/rcis_school_new/webservice/system/all")
                .addQueryParameter("school_code", "RCISTHANE")
                .setTag("test")
                .setPriority(Priority.LOW)
                .build()
                .getAsJSONArray(new JSONArrayRequestListener() {
                    @Override
                    public void onResponse(JSONArray response) {
                        // do anything with response
                        Log.e("resp", String.valueOf(response));

                    }
                    @Override
                    public void onError(ANError error) {
                        // handle error
                        Log.e("resp", String.valueOf("error"));

                    }
                });
       



/////////////////////////////////////////////////

And code for upload image file also not working it gives me connection error
url="http://dev.efurtherance.com/rcis_school_new/webservice/teacher/update"
params=profile_image(image file),action,reference;
AndroidNetworking.upload("http://dev.efurtherance.com/rcis_school_new/webservice/teacher/update")
                .addMultipartFile("profile_image", new File(imgpath))
                .addMultipartParameter("action", "updateprofileimage")
                .addMultipartParameter("reference","T1038")
                .setPriority(Priority.HIGH)
                .build()
                .setUploadProgressListener(new UploadProgressListener() {
                    @Override
                    public void onProgress(long bytesUploaded, long totalBytes) {
                        // do anything with progress
                    }
                })
                .getAsJSONObject(new JSONObjectRequestListener() {
                    @Override
                    public void onResponse(JSONObject response) {
                        // do anything with response
                        Log.e("resp", String.valueOf(response));
                    }

                    @Override
                    public void onError(ANError error) {
                        // handle error
                        Log.e("resp", String.valueOf("error"));
                        if (error.getErrorCode() != 0) {
                            // received error from server
                            // error.getErrorCode() - the error code from server
                            // error.getErrorBody() - the error body from server
                            // error.getErrorDetail() - just an error detail
                            Log.e("onError errorCode : ", String.valueOf(error.getErrorCode()));
                            Log.e("onError errorBody : ", String.valueOf(error.getErrorBody()));
                            Log.e("onError errorDetail : ", String.valueOf(error.getErrorDetail()));
                            // get parsed error object (If ApiError is your class)
                        } else {
                            // error.getErrorDetail() : connectionError, parseError, requestCancelledError
                            Log.e("onError errorDetail : ", String.valueOf(error.getErrorDetail()));
                        }
                    }
                });
